import os

TOKEN = os.environ.get("TELEGRAM_API_TOKEN")
API_URL = os.environ.get("TELEGRAM_API_URL") or "http://127.0.0.1:8000/api/v1/"
RABBIT_URL = os.environ.get("RABBIT_URL")
REDIS_URL = os.environ.get("REDIS_URL")
API_KEY = os.environ.get("API_KEY")
BACKEND_URL = os.environ.get("BACKEND_URL")
BROKER_URL = os.environ.get("BROKER_URL")
DEBUG_CHANNEL = os.environ.get("TELEGRAM_DEBUG_CHANNEL") or -1002121702897
MAIN_CHANNEL = os.environ.get("TELEGRAM_MAIN_CHANNEL")
MAIN_CHANNEL_ANCHOR_MESSAGE = os.environ.get("TELEGRAM_MAIN_CHANNEL_ANCHOR_MESSAGE")
CHECK_ZAMENA_INTERVAL_END_HOUR = os.environ.get("CHECK_ZAMENA_INTERVAL_END_HOUR")
CHECK_ZAMENA_INTERVAL_MINUTES = os.environ.get("CHECK_ZAMENA_INTERVAL_MINUTES")
CHECK_ZAMENA_INTERVAL_START_HOUR = os.environ.get("CHECK_ZAMENA_INTERVAL_START_HOUR")
SCHEDULER_SUPABASE_ANON_KEY = os.environ.get("SCHEDULER_SUPABASE_ANON_KEY")
SCHEDULER_SUPABASE_URL = os.environ.get("SCHEDULER_SUPABASE_URL")
