import os

TOKEN = os.environ.get("TELEGRAM_API_TOKEN")
API_URL = os.environ.get("TELEGRAM_API_URL")
RABBIT_URL = os.environ.get("RABBIT_URL")
REDIS_URL = os.environ.get("REDIS_URL")
API_KEY = os.environ.get("API_KEY")
BACKEND_URL = os.environ.get("BACKEND_URL")
BROKER_URL = os.environ.get("BROKER_URL")
DEBUG_CHANNEL = -1002121702897
MAIN_CHANNEL = -1002294769911
MAIN_CHANNEL_ANCHOR_MESSAGE = 2